-- Igreja Metodista Central de Teresópolis
-- Rode este script no SQL Editor do Supabase.
-- Pode rodar de novo: não apaga tabela e não dá DROP.
-- Senhas e chaves não ficam neste arquivo.
--
-- O Flask conecta como postgres e não é barrado pelo RLS.
-- A chave anônima não lê estas tabelas, porque não há política de acesso.

CREATE TABLE IF NOT EXISTS subsedes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    endereco TEXT NOT NULL DEFAULT '',
    bairro TEXT NOT NULL DEFAULT '',
    cidade TEXT NOT NULL,
    uf TEXT NOT NULL,
    cep TEXT NOT NULL DEFAULT '',
    telefone TEXT NOT NULL DEFAULT '',
    whatsapp TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    instagram_url TEXT NOT NULL DEFAULT '',
    pastor_responsavel TEXT NOT NULL DEFAULT '',
    horarios_culto TEXT NOT NULL DEFAULT '',
    mapa_url TEXT NOT NULL DEFAULT '',
    imagem_url TEXT NOT NULL DEFAULT '',
    eh_sede BOOLEAN NOT NULL DEFAULT FALSE,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    ordem INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Só uma subsede pode ser a sede.
CREATE UNIQUE INDEX IF NOT EXISTS idx_subsedes_uma_sede
    ON subsedes (eh_sede)
    WHERE eh_sede IS TRUE;

CREATE TABLE IF NOT EXISTS congregados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    subsede_id INTEGER REFERENCES subsedes (id) ON DELETE SET NULL,
    recebe_noticias BOOLEAN NOT NULL DEFAULT TRUE,
    token_descadastro TEXT NOT NULL DEFAULT gen_random_uuid()::text UNIQUE,
    data_cadastro TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- E-mail único sem diferenciar maiúsculas.
CREATE UNIQUE INDEX IF NOT EXISTS idx_congregados_email_lower
    ON congregados (lower(email));

CREATE INDEX IF NOT EXISTS idx_congregados_subsede_id
    ON congregados (subsede_id);

CREATE TABLE IF NOT EXISTS campanhas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descricao TEXT NOT NULL DEFAULT '',
    meta NUMERIC(12, 2) NOT NULL DEFAULT 0,
    arrecadado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    unidade TEXT NOT NULL DEFAULT 'R$',
    status TEXT NOT NULL DEFAULT 'ativa',
    imagem_url TEXT NOT NULL DEFAULT '',
    data_inicio DATE,
    data_fim DATE,
    subsede_id INTEGER REFERENCES subsedes (id) ON DELETE SET NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_campanhas_status CHECK (status IN ('ativa', 'encerrada')),
    CONSTRAINT ck_campanhas_valores CHECK (meta >= 0 AND arrecadado >= 0)
);

CREATE TABLE IF NOT EXISTS eventos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descricao TEXT NOT NULL DEFAULT '',
    data_evento TIMESTAMPTZ NOT NULL,
    data_fim TIMESTAMPTZ,
    dia_inteiro BOOLEAN NOT NULL DEFAULT FALSE,
    local TEXT NOT NULL DEFAULT '',
    subsede_id INTEGER REFERENCES subsedes (id) ON DELETE SET NULL,
    imagem_url TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'ativo',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_eventos_status CHECK (status IN ('ativo', 'encerrado', 'cancelado'))
);

CREATE INDEX IF NOT EXISTS idx_eventos_data_evento
    ON eventos (data_evento);

CREATE TABLE IF NOT EXISTS informativos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    tipo TEXT NOT NULL,
    conteudo_url TEXT NOT NULL DEFAULT '',
    texto TEXT NOT NULL DEFAULT '',
    link_url TEXT NOT NULL DEFAULT '',
    destaque BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    ordem INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_informativos_tipo CHECK (tipo IN ('banner', 'foto', 'video', 'aviso'))
);

CREATE TABLE IF NOT EXISTS feriados_locais (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    dia INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    ano INTEGER,
    tipo TEXT NOT NULL,
    CONSTRAINT ck_feriados_locais_dia CHECK (dia >= 1 AND dia <= 31),
    CONSTRAINT ck_feriados_locais_mes CHECK (mes >= 1 AND mes <= 12),
    CONSTRAINT ck_feriados_locais_ano CHECK (ano IS NULL OR ano >= 1900),
    CONSTRAINT ck_feriados_locais_tipo CHECK (
        tipo IN ('estadual', 'municipal', 'ponto_facultativo')
    )
);

CREATE TABLE IF NOT EXISTS configuracoes (
    id INTEGER PRIMARY KEY,
    nome_igreja TEXT NOT NULL,
    slogan TEXT NOT NULL DEFAULT '',
    instagram_url TEXT NOT NULL DEFAULT '',
    instagram_usuario TEXT NOT NULL DEFAULT '',
    youtube_url TEXT NOT NULL DEFAULT '',
    facebook_url TEXT NOT NULL DEFAULT '',
    whatsapp TEXT NOT NULL DEFAULT '',
    email_contato TEXT NOT NULL DEFAULT '',
    endereco TEXT NOT NULL DEFAULT '',
    sobre TEXT NOT NULL DEFAULT '',
    CONSTRAINT ck_configuracoes_id CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS administradores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS comunicados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal TEXT NOT NULL,
    assunto TEXT NOT NULL DEFAULT '',
    mensagem TEXT NOT NULL DEFAULT '',
    evento_id INTEGER REFERENCES eventos (id) ON DELETE SET NULL,
    campanha_id INTEGER REFERENCES campanhas (id) ON DELETE SET NULL,
    subsede_id INTEGER REFERENCES subsedes (id) ON DELETE SET NULL,
    total_destinatarios INTEGER NOT NULL DEFAULT 0,
    total_enviados INTEGER NOT NULL DEFAULT 0,
    erro TEXT,
    enviado_por TEXT NOT NULL DEFAULT '',
    enviado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_comunicados_canal CHECK (canal IN ('email', 'whatsapp'))
);

ALTER TABLE subsedes ENABLE ROW LEVEL SECURITY;
ALTER TABLE congregados ENABLE ROW LEVEL SECURITY;
ALTER TABLE campanhas ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE informativos ENABLE ROW LEVEL SECURITY;
ALTER TABLE feriados_locais ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE administradores ENABLE ROW LEVEL SECURITY;
ALTER TABLE comunicados ENABLE ROW LEVEL SECURITY;

-- Sede. Não duplica se já existir uma linha marcada como sede.
INSERT INTO subsedes (nome, cidade, uf, eh_sede, ativa, ordem)
SELECT 'Igreja Metodista Central', 'Teresópolis', 'RJ', TRUE, TRUE, 0
WHERE NOT EXISTS (
    SELECT 1 FROM subsedes WHERE eh_sede IS TRUE
);

INSERT INTO configuracoes (id, nome_igreja, endereco)
VALUES (1, 'Igreja Metodista Central', 'Teresópolis - RJ')
ON CONFLICT (id) DO NOTHING;

-- Conferir estas datas com o calendário da Prefeitura de Teresópolis.
-- O painel administrativo também mostra esse aviso.
INSERT INTO feriados_locais (nome, dia, mes, ano, tipo)
SELECT 'São Jorge', 23, 4, NULL, 'estadual'
WHERE NOT EXISTS (
    SELECT 1 FROM feriados_locais
    WHERE nome = 'São Jorge' AND dia = 23 AND mes = 4 AND tipo = 'estadual'
);

INSERT INTO feriados_locais (nome, dia, mes, ano, tipo)
SELECT 'Aniversário de Teresópolis', 6, 7, NULL, 'municipal'
WHERE NOT EXISTS (
    SELECT 1 FROM feriados_locais
    WHERE nome = 'Aniversário de Teresópolis' AND dia = 6 AND mes = 7 AND tipo = 'municipal'
);

INSERT INTO feriados_locais (nome, dia, mes, ano, tipo)
SELECT 'Santa Teresa', 15, 10, NULL, 'municipal'
WHERE NOT EXISTS (
    SELECT 1 FROM feriados_locais
    WHERE nome = 'Santa Teresa' AND dia = 15 AND mes = 10 AND tipo = 'municipal'
);

-- Bucket público das imagens. O backend envia com a SUPABASE_SERVICE_KEY.
-- Quem visita o site só consegue ler. Não há política de upload para a chave anônima.
INSERT INTO storage.buckets (id, name, public)
VALUES ('midia', 'midia', TRUE)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'storage'
          AND tablename = 'objects'
          AND policyname = 'midia_leitura_publica'
    ) THEN
        CREATE POLICY midia_leitura_publica
            ON storage.objects
            FOR SELECT
            USING (bucket_id = 'midia');
    END IF;
END
$$;

-- Primeiro administrador do painel.
-- 1. Crie o usuário no Supabase Auth (Authentication > Users) com e-mail e senha.
-- 2. Troque o e-mail de exemplo pelo mesmo e-mail e rode só o INSERT abaixo.
-- A senha não fica neste arquivo: ela é a do Supabase Auth.
--
-- INSERT INTO administradores (email, nome, ativo)
-- VALUES ('admin@exemplo.com', 'Administrador', TRUE);
